AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Amazon Redshift cookbook Chapter6
Parameters:
  CookbookIAMUserName:
    Type: String
    Description: cookbook iam user name
    Default: ''
  CookbookBucketName:
    Type: String
    Description: >-
      Session name must satisfy regular expression pattern
      ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
    Default: ''
  RedshiftClusterRole:
    Type: String
    Description: redshift cluster role name
    Default: ''
  IAMIdCInstanceID:
    Type: String
    Description: IAM Identity Center Instance ID
    Default: ''
  AccountId:
    Type: String
    Description: AWS Account ID
    Default: ''    
Resources:
            
  Chapter6IAMPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: Chapter6IAMPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'redshift:*'
              - 'redshift-data:*'
              - 'redshift-serverless:*'
              - 'secretsmanager:*'
              - 'logs:*'
              - 'ec2:*'
              - 'sns:*'
              - 'cloudwatch:*'
              - 'iam:*'
              - 'cloudformation:*'
              - 'kms:*'
              - 'glue:*'
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation   
              - 'sso:*'              
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${CookbookBucketName}"
              - !Sub "arn:aws:s3:::${CookbookBucketName}/*"  
                       
      Users:
        - !Ref CookbookIAMUserName
  Chapter6RedshiftPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${CookbookBucketName}'
              - !Sub 'arn:aws:s3:::${CookbookBucketName}/*'
          - Effect: Allow
            Action:
              - glue:*  
            Resource:
              - '*'      
          - Effect: Allow
            Action:
              - sso:*  
            Resource:
              - !Sub "arn:aws:sso:::instance/${IAMIdCInstanceID}",
              - !Sub "arn:aws:sso::${AccountId}:application/${IAMIdCInstanceID}/*"    
          - Effect: Allow
            Action:
              - 'redshift:DescribeQev2IdcApplications',
              - 'redshift-serverless:ListNamespaces',
              - 'redshift-serverless:ListWorkgroups',
              - 'redshift-serverless:GetWorkgroup' 
            Resource:
              - '*'
               
      Roles:
        - !Ref RedshiftClusterRole
Outputs:
  Chapter6IAMPolicy:
    Description: IAM policy access for chapter 6
    Value: !Ref Chapter6IAMPolicy
  Chapter6RedshiftPolicy:
    Description: Chapter6 redshift policy
    Value: !Ref Chapter6RedshiftPolicy
