AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  NamespaceName:
    Description: The name for namespace, which is a collection of database objects and users
    Type: String
  WorkgroupName:
    Description: The name for workgroup, which is a collection of compute resources
    Type: String
  BaseRPU:
    Description: Base RPU for Redshift Serverless Workgroup.
    Type: Number
    MinValue: '8'
    MaxValue: '1024'
    Default: '8'
    AllowedValues:
      - 8
      - 16
      - 32
      - 40
      - 48
      - 56
      - 64
      - 72
      - 80
      - 88
      - 96
      - 104
      - 112
      - 120
      - 128
      - 136
      - 144
      - 152
      - 160
      - 168
      - 176
      - 184
      - 192
      - 200
      - 208
      - 216
      - 224
      - 232
      - 240
      - 248
      - 256
      - 264
      - 272
      - 280
      - 288
      - 296
      - 304
      - 312
      - 320
      - 328
      - 336
      - 344
      - 352
      - 360
      - 368
      - 376
      - 384
      - 392
      - 400
      - 408
      - 416
      - 424
      - 432
      - 440
      - 448
      - 456
      - 464
      - 472
      - 480
      - 488
      - 496
      - 504
      - 512
      - 1024
  DatabaseName:
    Description: The name of the first database to be created in the serverless data
      warehouse
    Type: String
    Default: dev
    AllowedPattern: ([a-z]|[0-9])+
  AdminUsername:
    Description: The user name that is associated with the admin user account for
      the serverless data warehouse
    Type: String
    Default: awsuser
    AllowedPattern: ([a-z])([a-z]|[0-9])*
  AdminPassword:
    Description: The password that is associated with the admin user account for the
      serverless data warehouse. Default is Awsuser123
    Type: String
    Default: Awsuser123
    NoEcho: 'true'
    MinLength: '8'
    MaxLength: '64'
    AllowedPattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[^\x00-\x20\x22\x27\x2f\x40\x5c\x7f-\uffff]+
Resources:
  Namespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: !Ref NamespaceName
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminPassword
      DbName: !Ref DatabaseName
  Workgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      NamespaceName: !Ref NamespaceName
      WorkgroupName: !Ref WorkgroupName
      BaseCapacity: !Ref BaseRPU
      PubliclyAccessible: false
    DependsOn:
      - Namespace
  RedshiftServerlessSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RedshiftServerlessSecret
      Description: This secret is for Redshift Serverless
      SecretString: '{"username":"awsuser","password":"Awsuser123"}'
      Tags:
        - Key: RedshiftDataFullAccess
          Value: serverless
Outputs:
  NamespaceName:
    Description: Namespace Name
    Value: !Ref NamespaceName
  Workgroupname:
    Description: Workgroup Name
    Value: !Ref WorkgroupName
  AdminUsername:
    Description: Username to login to your Redshift cluster
    Value: !Ref AdminUsername
  AdminPassword:
    Description: Username to login to your Redshift cluster
    Value: !Ref AdminPassword
  RedshiftServerlessEndpoint:
    Description: Redshift Serverless endpoint
    Value: 
      Fn::Join: 
        - ':'
        - - Fn::GetAtt: [Workgroup, Workgroup.Endpoint.Address]
          - "5439"